#entry
GET http://localhost:3001

###
# All persons
GET http://localhost:3001/api/persons

###
# Phonebook info
GET http://localhost:3001/info

###
# Single person
GET http://localhost:3001/api/persons/<id>
