# add person
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Dae Do",
  "number": "030-433-3398"
}

###
# update name or content
PUT http://localhost:3001/api/persons/<id> HTTP/1.1
Content-Type: application/json

{
  "name": "Hummie",
  "number": "031d-323-2323"
}
